name: Builds
run-name: Builds - ${{ github.event.head_commit.message }}

on:
   push:
   pull_request:
   workflow_dispatch:

jobs:
  build:
    name: Build matid ${{ matrix.matid }} ${{ matrix.compilerEnv }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.GithubActionsIgnoreFail }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - matid: 01
            os: windows-2025
            compilerEnv: cygwin
            GithubActionsIgnoreFail: false

          - matid: 02
            os: windows-2025
            compilerEnv: MINGW32
            shellEnv: msys2 {0}
            GithubActionsIgnoreFail: true

          - matid: 03
            os: windows-2025
            compilerEnv: UCRT64
            shellEnv: msys2 {0}
            GithubActionsIgnoreFail: true

    defaults:
      run:
        shell: ${{ matrix.shellEnv || 'bash' }}

    steps:

      - name: I am Powershell on ${{ matrix.os }}
        if: ${{ matrix.os == 'windows-2025'}}
        shell: powershell
        run: |
          echo "I am Powershell"

      - name: I am Cmd on ${{ matrix.os }}
        if: ${{ matrix.os == 'windows-2025' }}
        shell: cmd
        run: |
          echo "I am Cmd."

      - name: Install Windows mingw Software on ${{ matrix.compilerEnv }}
        if: ${{ matrix.os == 'windows-2025' && ( matrix.compilerEnv == 'UCRT64' || matrix.compilerEnv == 'MINGW32' ) }}
        uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: strict
          msystem: ${{ matrix.compilerEnv }}
          install: >-
            ${{ env.MINGW_PACKAGE_PREFIX }}-diffutils

      - name: Set Variables on ${{ matrix.compilerEnv }}
        if: ${{ matrix.os == 'windows-2025' && ( matrix.compilerEnv == 'UCRT64' || matrix.compilerEnv == 'MINGW32' ) }}
        env:
          # Msys OS variable
          msystem: ${{ matrix.compilerEnv }}
        run: |
          set -x -v -e
          if [ "${{ matrix.compilerEnv }}" == "MINGW32" ]; then export MINGW_PACKAGE_PREFIX="mingw-w64-i686"        ; fi
          if [ "${{ matrix.compilerEnv }}" == "UCRT64"  ]; then export MINGW_PACKAGE_PREFIX="mingw-w64-ucrt-x86_64" ; fi
          echo "MINGW_PACKAGE_PREFIX=${MINGW_PACKAGE_PREFIX}" >> ${GITHUB_ENV}
          echo "MINGW_PACKAGE_PREFIX: ${MINGW_PACKAGE_PREFIX}"

      - name: Install Windows mingw Software Packages on ${{ matrix.compilerEnv }}
        if: ${{ matrix.os == 'windows-2025' && ( matrix.compilerEnv == 'UCRT64' || matrix.compilerEnv == 'MINGW32' ) }}
        env:
          # Msys OS variable
          msystem: ${{ matrix.compilerEnv }}
        run: |
          set -x -v -e
          echo "MINGW_PACKAGE_PREFIX: ${MINGW_PACKAGE_PREFIX}"
          pacman --noconfirm -S --needed  ${{ env.MINGW_PACKAGE_PREFIX }}-7zip
